// <auto-generated />
using DevTranslate.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevTranslate.Api.Migrations
{
    [DbContext(typeof(DevTranslateContext))]
    [Migration("20190706234036_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DevTranslate.Api.Entities.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnName("author")
                        .HasMaxLength(150);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnName("imageUrl");

                    b.Property<int>("Language")
                        .HasColumnName("language");

                    b.Property<int>("Status")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasMaxLength(250);

                    b.Property<string>("Translator")
                        .IsRequired()
                        .HasColumnName("translator")
                        .HasMaxLength(200);

                    b.Property<int>("Type")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("translations");
                });
#pragma warning restore 612, 618
        }
    }
}
