// <auto-generated />
using DevTranslate.Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevTranslate.Api.Migrations
{
    [DbContext(typeof(DevTranslateContext))]
    partial class DevTranslateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DevTranslate.Api.Entities.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("ImageUrl");

                    b.Property<int>("Language");

                    b.Property<int>("Status");

                    b.Property<string>("Title");

                    b.Property<int>("TranslationType");

                    b.Property<string>("Translator");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Translations");

                    b.HasData(
                        new { Id = 1, Author = "Gajus Kuizinas", ImageUrl = "https://image.ibb.co/b9GdKb/1.png", Language = 1, Status = 1, Title = "Pare de usar CSS no JavaScript para desenvolvimento web", TranslationType = 1, Translator = "Carlos Eduardo Olivieri", Url = "https://medium.com/@cadutech/pare-de-usar-css-no-javascript-para-desenvolvimento-web-b4a2e8fbb85e" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
